version: "3"

services:
  api:
    container_name: app-java
    image: paiva2/app-java:2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
