spring:
  application:
    name: terraform
  cloud:
    aws:
      region:
        static: us-east-2
      sqs:
        listener:
          auto-create-queue: false
        queue-not-found-strategy: fail

aws:
  sqs:
    queue: "application-queue-paiva2-java-app.fifo"
  sns:
    topic: "tf-sns.fifo"

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error